### PR TITLE
add rus loc

### PR DESCRIPTION
**Pull request by shikulja**

### CODE REVIEW

**Comment by myst6re** [comment]
Thanks! I review it later 👍

**Comment by myst6re** [comment]
Is it ready yet?

**Comment by shikulja** [comment]
@myst6re 
All I know, I added and corrected.
Some messages are not translated, but this is not so important, well, the .ts files need to be updated, since some new lines are not included in the translation file:
image
image

So, the translation can be added, it is quite correct.

**Comment by myst6re** [comment]
I added missing translations in release/0.12.0 branch, is it possible for you to update the Russian language file this weekend before the next release?

**Comment by shikulja** [comment]
@myst6re I'll see tomorrow, Sunday

**Comment by myst6re** [comment]
Perfect, thanks!

**Pull request merged**
